# Generated by Django 4.0.2 on 2022-03-15 19:47

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='normaluser', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='prn',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
    ]
