# Generated by Django 4.0.2 on 2022-03-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prn',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
