# Generated by Django 4.0.2 on 2022-03-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
